CREATE TABLE IF NOT EXISTS "clubs" (
   "id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
   "name" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "nations" (
   "id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
   "name" VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "players" (
   "id" INTEGER NOT NULL UNIQUE PRIMARY KEY,
   "name" VARCHAR(255),
   "position" VARCHAR(3),
   "nation_id" INTEGER,
   "club_id" INTEGER
);

CREATE TABLE IF NOT EXISTS "users" (
   "id" SERIAL NOT NULL PRIMARY KEY,
   "name" VARCHAR(200) NOT NULL,
   "email" VARCHAR(255) UNIQUE NOT NULL,
   "password" VARCHAR(255) NOT NULL,
   "token" TEXT,
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "update_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "delete_at" TIMESTAMPTZ
);
